# Generated by Django 2.1.3 on 2019-09-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_page',
            field=models.CharField(default='', max_length=10),
        ),
    ]
