# Generated by Django 2.1.3 on 2019-10-01 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_user_book_currently_reading_user_book_reading_user_book_wishlisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intermediate_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.CharField(default='', max_length=10)),
                ('status', models.CharField(default='Not Read', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='current_page',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AlterField(
            model_name='user_book_currently_reading',
            name='book',
            field=models.ManyToManyField(to='books.Intermediate_Book'),
        ),
        migrations.AlterField(
            model_name='user_book_reading',
            name='book',
            field=models.ManyToManyField(to='books.Intermediate_Book'),
        ),
        migrations.AlterField(
            model_name='user_book_wishlisted',
            name='book',
            field=models.ManyToManyField(to='books.Intermediate_Book'),
        ),
        migrations.AddField(
            model_name='intermediate_book',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_as_inter_book', to='books.Book'),
        ),
        migrations.AddField(
            model_name='intermediate_book',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_as_inter_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
