# Generated by Django 2.1.3 on 2019-10-01 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20191001_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediate_book',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='intermediate_book',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
