# Generated by Django 2.1.3 on 2019-10-02 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20191001_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediate_book',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
