# Generated by Django 2.1.3 on 2019-10-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20191002_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_book_currently_reading',
            name='book',
        ),
        migrations.AddField(
            model_name='user_book_currently_reading',
            name='book',
            field=models.ManyToManyField(to='books.Intermediate_Book'),
        ),
        migrations.RemoveField(
            model_name='user_book_reading',
            name='book',
        ),
        migrations.AddField(
            model_name='user_book_reading',
            name='book',
            field=models.ManyToManyField(to='books.Intermediate_Book'),
        ),
        migrations.RemoveField(
            model_name='user_book_wishlisted',
            name='book',
        ),
        migrations.AddField(
            model_name='user_book_wishlisted',
            name='book',
            field=models.ManyToManyField(to='books.Intermediate_Book'),
        ),
    ]
